### ISSUE TITLE
Links to files in news feed

### ISSUE THREAD

**Issue by raamana** [INCF/niQC#14]
Hi @anibalsolon ,

can you take a look at https://incf.github.io/niQC/news/sigMeetingOhbm2019 and see why links to images and PDFs in the same folder don't work? 

Thanks.

**Comment by anibalsolon** [comment]
Hi @raamana 

yes, it is fixed now. I installed a plugin that extracts the files from markdown and moves it to a `static` folder.

**Comment by raamana** [comment]
that works, thanks! :)
