### ISSUE TITLE
Improve documentation on how to collaborate

### ISSUE THREAD

**Issue by anibalsolon** [INCF/niQC#2]
Update README.md with details about how it works and how to edit it.

**Comment by raamana** [comment]
Hi Annibal, did you get a chance to work on this?

**Comment by anibalsolon** [comment]
Hi @raamana 

I've updated it with the basic structure of the repo, could you give some directions on how to improve it?

**Comment by raamana** [comment]
Thanks, that's great and helpful now. I had to install gatsby for some reason, but perhaps that might not be needed for everyone.

We might have to distinguish between blog posts (news) and regular pages.

As I use it, I will also update README.

**Comment by anibalsolon** [comment]
Cool!

Yes, I guess I also need to add some documentation on how to develop and
test locally.

**Comment by raamana** [comment]
Exactly - I was just about to say the same. How can I check how the commit changes the website before I push it to remote?

**Comment by raamana** [comment]
I added a new page Get Involved with latest commits
https://circleci.com/gh/INCF/niQC/41

it doesn't seem to get added to the website - perhaps I missed a step in creating and adding a new page?

**Comment by anibalsolon** [comment]
Hi @raamana 

About the page you created, it is deployed in https://incf.github.io/niQC/getinvolved
I will add an extra meta-data field for pages to indicate if it should appear on the header menu, and in which order.

**Comment by raamana** [comment]
Thanks.

I thought the header is generated automatically! I guess I am wrong.

**Comment by raamana** [comment]
header menu is managed by editing `NavBar` in `src/layouts/NavBar.jsx` ?

**Comment by anibalsolon** [comment]
Yes, in a list of <Link> elements!

**Comment by anibalsolon** [comment]
So no it is not a list anymore, I will update the README on how it works now.

**Comment by raamana** [comment]
Okay - please do.

I added another new page Resources
https://github.com/INCF/niQC/commit/adb9d89b90cb89a6c64b25996c2911f8bd98ae79

it doesn't seem to show up on the live page yet.

**Comment by anibalsolon** [comment]
Sometimes it may take some time, given Github Pages cache
