### ISSUE TITLE
card is not visible in the home page 

### ISSUE THREAD

**Issue by aashimawadhwa** [INCF/niQC#29]
second card is not there in the homepage .

![Screenshot from 2022-02-10 23-43-08](https://user-images.githubusercontent.com/73706697/153471979-9a9cf4b6-aec7-42ae-a2b8-6b081f5540a2.png)

**Comment by raamana** [comment]
thanks Aashima, do you mean there is no image thumbnail for the second items in news titled "Phantom QA/QC"?

**Comment by KhanalGaurab** [comment]
I want to work on this issue. Please assign me this issue.

**Comment by avnis838** [comment]
I want correct the isssue, if assigned.

**Comment by ShubhamAgarwal-11** [comment]
@aashimawadhwa Can you tell me which picture to put?

**Comment by om-verma-03** [comment]
Plzz give the image to put on in Place of Card

**Comment by draunger** [comment]
@raamana I saw there is one card which is not displaying in the homepage can I do that?
