### ISSUE TITLE
Hearder is seen transperently with the website page when we scroll up.

### ISSUE THREAD

**Issue by IswarPatro** [INCF/niQC#59]
In the website https://incf.github.io/niQC/ when we scroll down and up i can see there is a transperently merging of header with website home page.

**Comment by IswarPatro** [comment]
I want to work on this issue please assign me this issue.

**Comment by raamana** [comment]
thansk @IswarPatro - it would be great to take your help. how would you fix it? make it less transparent?

**Comment by Inzamamdev** [comment]
Can make the navbar as sticky navbar

**Comment by IswarPatro** [comment]
Thanks @raamana for your response.I am participating in GSoC 2023 for that reason i am not able to check my past issue raise.I make navbar sticky .Also navbar have some design and css changes if you assign me this i will fix this issues.

**Comment by Amanyadav207** [comment]
As the issue is still open, Please let me know the status of the issue. If the issue is still open, I am eager to work on this is issue. I have experience in HTML,CSS,Python and Java.Please assign the issue to me.

**Comment by raamana** [comment]
it is still open!

**Comment by Amanyadav207** [comment]
Hi @raamana what is the expected behavior we want this issue.
I have multiple thoughts like:
1. we can make the header sticky
2. remove the transparency effect completely
3.  or we can disable the header appearance effect while scrolling up on the website.

Please let me know I will open the PR accordingly

**Comment by Amanyadav207** [comment]
hi @raamana could you please reply to the above comment . I am still interested in this

**Comment by raamana** [comment]
Sure, go ahead with your suggestion!

**Comment by Amanyadav207** [comment]
hi @raamana can please tell what have to be done out these .So that i can open PR accordingly
> * we can make the header sticky
> * remove the transparency effect completely
> * or we can disable the header appearance effect while scrolling up on the website.

**Comment by raamana** [comment]
all of them

**Comment by Ayush-Vish** [comment]
@Amanyadav207   Are you still working on this issue  ?  
If not please let me know.

**Comment by Amanyadav207** [comment]
No I am not working on it

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Aryann15** [comment]
HI @raamana since Amanya is not working on this issue, Can I start working on this now?  Please let me know. Thanks!

**Comment by raamana** [comment]
never mind - i'm closing this for now.
