### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by raamana** [INCF/niQC#7]
Thanks for adding the RSS feed functionality.. Perhaps we need to expose the RSS feed somewhere - I'd suggest on the home page itself, so they can get it directly.

I am also wondering if we can add in a newsletter functionality? Would that be possible with this template?  we can use the INCF web servers if needed to maintain the list, or find out if there are free solutions.

**Comment by raamana** [comment]
Hi @anibalsolon, did you find a solution for this yet? It’s not urgent but will be nice to have - we will have traffic before/during/after OHBM. If you don’t have time, it’s completely fine, just tell me what to do. Thanks.

**Comment by anibalsolon** [comment]
Hi Pradeep,

I suggest to go with a solution like MailChimp, it can handle the
newsletter.

Anibal Solon
Assistant Research Scientist
Computational Neuroimaging Laboratory
p: 646.625.4378
e: anibal.solon@childmind.org <steven.giavasis@childmind.org>

Child Mind Institute
445 Park Avenue (entrance on 56th Street)
New York, NY 10022
childmind.org <https://aidbox.org/ct/?i=638132000000914&t=1>

**Comment by raamana** [comment]
Mailchimp may not work without paying money!

What about this?
https://www.gatsbyjs.org/docs/adding-an-rss-feed/

**Comment by anibalsolon** [comment]
I mean Mailchimp for the newsletter, to send out e-mails.

We use this plugin, just need to include a link to the RSS so the user can see. Any RSS aggregator can include the website as a feed, since it has the required HTML RSS tags (e.g. <link rel="alternate" type="application/rss+xml" title="niQC RSS Feed" href="/niQC/rss.xml"/> )

**Comment by raamana** [comment]
great to hear that - let's put it on home page, and in the get involved page. thanks.

**Comment by raamana** [comment]
Hey! can we try to get this done today or tmrw if possible?

**Comment by anibalsolon** [comment]
Yes! Please take a look on the website, and let me know if this is what you had in mind.

**Comment by raamana** [comment]
This works, wonderful.
