### ISSUE TITLE
Layout in small screens

### ISSUE THREAD

**Issue by raamana** [INCF/niQC#8]
Current layout does not generalize to mobiles and small windows on desktops. Perhaps a config issue?

cc @anibalsolon

**Comment by raamana** [comment]
Menu is not dynamic and is the main issue

**Comment by raamana** [comment]
I tried to read the docusaurus docs, but it wasn't clear to me how to change the config, or even if its possible. Did you get a chance to think about this?

**Comment by anibalsolon** [comment]
@raamana it is about the layout/css. We use [Gatsby](https://www.gatsbyjs.org/) now, instead of docusaurus.

I think we might need something like this:

https://blog.teamtreehouse.com/create-an-absolute-basic-mobile-css-responsive-navigation-menu

**Comment by raamana** [comment]
cool - didn't realize that.

Anything that works and is easy is fine with me. Go ahead with that menu.

**Comment by anibalsolon** [comment]
Hi @raamana 

It is done now! I just need to figure out how to display the tool's tables, because they overflow the page and break it.

**Comment by raamana** [comment]
Looks Great!

Tables look okay to me in landscape mode. If it’s more than trivial, don’t bother.

**Comment by anibalsolon** [comment]
I've added scrollbars when in a mobile screen.
